### PR TITLE
Optimize search engine

### PR DESCRIPTION
**Pull request by miketvo**
Bugfixes:

1. Removed flawed search_relevance calculations
2. Fixed database loading bug: Duplicate ids between stores and products
3. Sort search results by most recent

### CODE REVIEW

**Review by rider3458 — CHANGES_REQUESTED** [review]
Stores in "Technology stores" category have bigger cards. Keywords "boeing" and "enel" can be used to check the issue. The padding for store category is the reason to the difference in those cards compared to the others.

**Review by tnathu-ai — CHANGES_REQUESTED** [review]
**Bugs:**
+ Unable to search for word inside keyword or search word by word (e.g. mcdonald vs. mcdonald's) 
+ Unable to search for any keyword if there is space(s) at the end of the search term

**Possible solutions:**
+ Separate all the search terms into individual words by using the explode function and turn the string into an array
`    $search_term = explode(' ', $q);
    foreach ($search_term as $word){
    }`
+ trim() the inputs inside the searchbar

**Review by doanyennhi — CHANGES_REQUESTED** [review]
When displaying search results, the price is not displayed correctly, the decimal part is not shown

**Review by rider3458 — APPROVED** [review]

**Review by tnathu-ai — APPROVED** [review]
Great. 
Can implement search word by word later (e.g., Team Guard SRL 1 vs. TeamGuard SRL 1)

**Review by doanyennhi — APPROVED** [review]

**Pull request merged**
